### PR TITLE
Norwegian phone numbers can also start with a 9

### PR DESCRIPTION
**Pull request by MarkNijhof**

### CODE REVIEW

**Comment by fcevado** [comment]
Thank you for the PR. I'll merge the PR but I wont make a new release, I'm preparing some  changes to improve performance.

**Comment by MarkNijhof** [comment]
Ok, I'll keep using my fork until then. Do you have a timeline for the release?

**Comment by fcevado** [comment]
I'm traveling this week(that's why I took so long to answer you, sorry for that), but I guess in the weekend I must finish it. If not, I'll make a release with this changes you made.

**Comment by MarkNijhof** [comment]
No rush, just asking when to check again :-) thanks for having this library!

**Pull request merged**
