### PR TITLE
Add tests for NANP area codes and support new area codes

### PR DESCRIPTION
**Pull request by aaronrenner**
I was having issues with missing area codes, so I exported all of the NANP area codes from our database and wrote some automated tests around them. This adds or fixes over 20 area codes. I double checked on wikipedia to double-check my data.

### CODE REVIEW

**Comment by fcevado** [comment]
Hello, @aaronrenner! This is your first Pull Request that will be reviewed by [Ebert](https://ebertapp.io/), an automatic Code Review service. It will leave comments on this diff with potential issues and style violations found in the code as you push new commits. You can also see all the issues found on this Pull Request on its [review page](https://ebertapp.io/github/fcevado/phone/pulls/83). Please check our [documentation](https://ebertapp.io/docs) for more information.

**Comment by fcevado** [comment]
Ebert has finished reviewing this Pull Request and has found:

* 1 possible new issue (including those that may have been commented here).

You can see more details about this review at https://ebertapp.io/github/fcevado/phone/pulls/83.

**Comment by fcevado** [comment]
@aaronrenner thank you a lot man. sorry for taking so long to merge. Thanks a lot for the test update.

**Comment by aaronrenner** [comment]
Thanks for all the work you do to maintain this library! It's great to have a phone number parsing library in elixir.

**Pull request merged**
